In [1]:
import torch
import numpy as np
import pandas as pd

# eval()
eval() 函数用来执行一个字符串表达式，并返回表达式的值。


In [1]:
x = 7
print(eval( '3 * x' ))
print(eval('pow(2,2)'))
print(eval('2 + 2'))
n=81
print(eval("n + 4"))

21
4
4
85


# list

In [2]:
x = [[1,2,4,5,6], [2,5,4,4,4,4,], [3,9,9,4,8,4,4,4,4,]] 
print(x)
print(x[0])
print(x[0][0])
print(type(x))

print()
list1 = ['physics', 'chemistry', 1997, 2000]
list2 = [1, 2, 3, 4, 5, 6, 7 ]
print ("list1[0]: ", list1[0])
print ("list2[1:5]: ", list2[1:5])
print(list1[-1])
print(list1[-2])
print(list1[1:])
for x in list1:
    print(x)

print()
list = []          ## 空列表
list.append('Google')   ## 使用 append() 添加元素
list.append('Runoob')
print (list)

print()
list1 = ['physics', 'chemistry', 1997, 2000]
print (list1)
del list1[2]
print ("After deleting value at index 2 : ")
print (list1)

print()
list1 = ['physics', 'chemistry', 1997, 2000]
list2 = [1, 2, 3, 4, 5, 6, 7 ]
print(len(list1))
print(list1+list2)
print(3 in list2)
# print(cmp(list1,list2))
print(max(list2))
print(min(list2))
list2.append(2)
print(list2.count(2))
print(list1.extend(list2))
print(list2.index(3))
print(list2.remove(3))
print(list2.reverse())
print(list2.sort())

[[1, 2, 4, 5, 6], [2, 5, 4, 4, 4, 4], [3, 9, 9, 4, 8, 4, 4, 4, 4]]
[1, 2, 4, 5, 6]
1
<class 'list'>

list1[0]:  physics
list2[1:5]:  [2, 3, 4, 5]
2000
1997
['chemistry', 1997, 2000]
physics
chemistry
1997
2000

['Google', 'Runoob']

['physics', 'chemistry', 1997, 2000]
After deleting value at index 2 : 
['physics', 'chemistry', 2000]

4
['physics', 'chemistry', 1997, 2000, 1, 2, 3, 4, 5, 6, 7]
True
7
1
2
None
2
None
None
None


# ndarray

In [3]:
import numpy as np

x = [[1,2,4,5,6], [2,5,4,4,4,4,], [3,9,9,4,8,4,4,4,4,]] 
y=np.array([1,2,3,4,9,9,9,9])
print(y)
print(type(y))
x = np.array(x)
print(x)
print(type(x))


[1 2 3 4 9 9 9 9]
<class 'numpy.ndarray'>
[list([1, 2, 4, 5, 6]) list([2, 5, 4, 4, 4, 4])
 list([3, 9, 9, 4, 8, 4, 4, 4, 4])]
<class 'numpy.ndarray'>


<ipython-input-3-ca7786503301>:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  x = np.array(x)


# dict

In [22]:
b=[1,2,3,4,]
a={word: idx for idx, word in enumerate(b)}
b={idx: word for idx, word in enumerate(b)}
print(a)
print(type(a))
print(b)

# 字典排序
dic = {'a':31, 'd':5, 'c':3, 'b':4, 'f':56, 'e':0}
print(dic)
# ips是字典，item[0]的话是对键排序，item[1]是对值排序，reverse = False是升序（默认），reverse = True是降序
print(sorted(dic.items(), key=lambda item:item[0], reverse = True))
print(sorted(dic.items(), key=lambda item:item[1], reverse = True))
print(sorted(dic.items(), key=lambda item:item[0], reverse = False))
print(sorted(dic.items(), key=lambda item:item[1], reverse = False))

sorted_dic=sorted(dic.items(), key=lambda item:item[1], reverse = False)
print(sorted_dic)

# 二维list取列，从sorted_dic中的每一行取第一个元素。
sorted = [i[0] for i in sorted_dic] 
print(sorted)

{1: 0, 2: 1, 3: 2, 4: 3}
<class 'dict'>
{0: 1, 1: 2, 2: 3, 3: 4}
{'a': 31, 'd': 5, 'c': 3, 'b': 4, 'f': 56, 'e': 0}
[('f', 56), ('e', 0), ('d', 5), ('c', 3), ('b', 4), ('a', 31)]
[('f', 56), ('a', 31), ('d', 5), ('b', 4), ('c', 3), ('e', 0)]
[('a', 31), ('b', 4), ('c', 3), ('d', 5), ('e', 0), ('f', 56)]
[('e', 0), ('c', 3), ('b', 4), ('d', 5), ('a', 31), ('f', 56)]
[('e', 0), ('c', 3), ('b', 4), ('d', 5), ('a', 31), ('f', 56)]
['e', 'c', 'b', 'd', 'a', 'f']


# str

In [5]:
a = 'Python is a powerful languange.'
print(type(a))
re_a = a[::-1]
print(re_a)

# 把列表的元素转化成一个字符串
string = ['a','b','c','d','e','f','g']
s=''.join(string)
print(s)

<class 'str'>
.egnaugnal lufrewop a si nohtyP
abcdefg


# 数据补齐或截断

In [6]:
from keras_preprocessing import sequence

MaxLen=15
x = [[1,2,4,5,6], [2,5,4,4,4,4,], [3,9,9,4,8,4,4,4,4,]]  # 特征
y = [2, 4, 6]  # 标签
print("原数据")
print(x)

# padding padding='post'or padding='pre'------------------------
print("在原数据后面填充")
# 用 0填充
x0=sequence.pad_sequences(x,maxlen=MaxLen,value=0,padding='post')
print(x0)   
print("在原数据前面填充")
x1=sequence.pad_sequences(x,maxlen=MaxLen,value=0,padding='pre')
print(x1)

# 截断 truncating='post' or truncating='pre'-----------
x = [[1,2,4,5,6], [2,5,4,4,4,4,], [3,9,9,4,8,4,4,4,4,]]  # 特征
y = [2, 4, 6]  # 标签
MaxLen=3
print("原数据")
print(x)
print("从原数据前面截断")
x0=sequence.pad_sequences(x,maxlen=MaxLen,value=0,truncating='post')
print(x0)
print("从原数据后面截断")
x1=sequence.pad_sequences(x,maxlen=MaxLen,value=0,truncating='pre')
print(x1)

原数据
[[1, 2, 4, 5, 6], [2, 5, 4, 4, 4, 4], [3, 9, 9, 4, 8, 4, 4, 4, 4]]
在原数据后面填充
[[1 2 4 5 6 0 0 0 0 0 0 0 0 0 0]
 [2 5 4 4 4 4 0 0 0 0 0 0 0 0 0]
 [3 9 9 4 8 4 4 4 4 0 0 0 0 0 0]]
在原数据前面填充
[[0 0 0 0 0 0 0 0 0 0 1 2 4 5 6]
 [0 0 0 0 0 0 0 0 0 2 5 4 4 4 4]
 [0 0 0 0 0 0 3 9 9 4 8 4 4 4 4]]
原数据
[[1, 2, 4, 5, 6], [2, 5, 4, 4, 4, 4], [3, 9, 9, 4, 8, 4, 4, 4, 4]]
从原数据前面截断
[[1 2 4]
 [2 5 4]
 [3 9 9]]
从原数据后面截断
[[4 5 6]
 [4 4 4]
 [4 4 4]]


# tensor 根据数据制作mask矩阵 与维度无关

In [7]:
import torch
import numpy as np

x=np.array([1,2,3,4,9,9,9,9])
x=torch.tensor(x)
mask = torch.logical_not(torch.eq(x, torch.tensor(9)))
print(x)
print(mask)
x1=np.array([[[1,2,3,4,9,9,9,9]]])
print(x1.shape)
x1=torch.tensor(x)
print(x1.shape)
mask = torch.logical_not(torch.eq(x1, torch.tensor(9)))
print(x1)
print(mask)

tensor([1, 2, 3, 4, 9, 9, 9, 9], dtype=torch.int32)
tensor([ True,  True,  True,  True, False, False, False, False])
(1, 1, 8)
torch.Size([8])
tensor([1, 2, 3, 4, 9, 9, 9, 9], dtype=torch.int32)
tensor([ True,  True,  True,  True, False, False, False, False])


<ipython-input-7-f5587617c37d>:11: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x1=torch.tensor(x)


# 根据mask矩阵对数据进行选择

In [8]:
import torch
import numpy as np

x=np.array([1,2,3,4,9,9,9,9])
x=torch.tensor(x)
mask = torch.logical_not(torch.eq(x, torch.tensor(9)))
print(type(mask))
print(mask)
print(torch.masked_select(x,mask))

<class 'torch.Tensor'>
tensor([ True,  True,  True,  True, False, False, False, False])
tensor([1, 2, 3, 4], dtype=torch.int32)


# crf库的使用

In [9]:
import torch
from torchcrf import CRF
 
num_tags = 5  # number of tags is 5
model = CRF(num_tags)
 
seq_length = 3  # maximum sequence length in a batch
batch_size = 2  # number of samples in the batch
 
hidden= torch.randn(batch_size,seq_length,num_tags)
print(hidden)
 
mask = torch.tensor([[1, 1,1], [1, 1,0]], dtype=torch.uint8)
 
tags = torch.tensor([[0,2,3], [1,4,1]], dtype=torch.long)  #(batch_size, seq_length)
 
model(hidden,tags,mask)  # 计算对数似然（用于向前）
 
model.decode(hidden,mask) # 解码（预测序列标签）

tensor([[[ 0.7994,  0.1552,  1.3501,  0.8890, -1.5365],
         [ 0.5299, -0.4725, -0.8275,  1.0648,  0.3474],
         [ 0.2667, -0.4837, -0.9915,  0.3845,  0.7956]],

        [[-1.1033, -1.1506,  0.3938, -0.5144, -0.7207],
         [ 1.0784, -0.3874,  0.9123,  0.5655,  0.4033],
         [-0.7794, -1.7296,  0.4512,  0.4451,  1.0375]]])


[[2, 2], [3, 0], [4]]

# tensor 维度变化
transpose只能选择tensor中两个维度进行转置，比如第1和2维转置：

In [25]:
a=[[1,3],[2,4],[5,6]]
print(a)
a=np.array([[1,3],[2,4],[5,6]])
print(type(a))
print(a)
print(a.shape)
a=a.transpose(1,0)
print(a)

[[1, 3], [2, 4], [5, 6]]
<class 'numpy.ndarray'>
[[1 3]
 [2 4]
 [5 6]]
(3, 2)
[[1 2 5]
 [3 4 6]]


获取形状tensor.size() tensor.shape，可以通过tensor.size()或者tensor.shape得到。这两者不同的是tensor.szie()调用的是方法，tensor.shape访问的是张量的属性。相同的是两者返回的结果的数据类型都为torch.Size

reshape 和view方法的结果是一致的，但是view没有开辟新的内存空间，而reshape开辟了新的内存空间。尽管reshape开辟了新的内存空间，但是指向的底层元素地址依旧没有变换 

In [51]:
a=np.array([[1,3],[2,4],[5,6]])

print(a.view(-1))

a.reshape((2,3,2))

TypeError: Cannot interpret '-1' as a data type

# 获取形状tensor.size() tensor.shape

In [32]:
import numpy as np
 
a = np.array([2,3.2])
print(a.dtype)
 
a = np.array([2,3])
print(a.dtype)
 
a.dtype = 'float32'
print(a.dtype)
 
a.dtype = 'float64'
print(a.dtype)

float64
int32
float32
float64


# tensor创建规则

In [ ]:
a1=torch.rand(3,3)#随机产生0-1之间的数值，不包括1
 
b1 = torch.randint(1,10,[3,3])#随机产生1-10之间的整数，其shape为(3,3)
 
c1=torch.normal(mean=torch.full([10],0),std=torch.arange(1,0,-0.1))
#均值全为0，方差为[1,0.9,...,0.1]
#第1个数据从N(0,1)中采样，第2个数据从N(0,0.9)中采样...第10个数据从N(0,0.1)中采样
 
d1=torch.randn(3,3)

# random 

https://blog.csdn.net/weixin_39374967/article/details/103655190

# 写代码的统一规范：随机种子设置

In [ ]:
SEED = 1210
def seed_everything(seed):
    random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
seed_everything(SEED) #设置几乎所有的随机种子 随机种子，可使得结果可复现

# 在写代码的时候 统一使用 FloatTensor:torch.float32类型进行计算：

PyTorch出现错误“RuntimeError: Found dtype Double but expected Float”

如果a[FloatTensor]和b[DoubleTensor]是两个参与运算的张量，且有运算代码“loss = criterion(a,b)”,则会引发上面的问题。

使用double()则会占用很多显存

过用double():torch.float64 进行运算，不过这样显存占用会增大许多，而很可能出现显存爆炸的情况，所以最后还是使用FloatTensor:torch.float32类型。

Pytorch里的tensor创建时默认是Torch.FloatTensor类型（torch.float32)

In [ ]:
torch.set_default_tensor_type(torch.FloatTensor) #如果想要创建变量类型都是Float32 类型
 
#创建 np.array的时候
a = np.array([2,3.2])
a.dtype = 'float32'

# numpy转 tensor
b=torch.from_numpy(a)# 数据类型不变 
 
# 创建tensor的时候
d=torch.FloatTensor([2,3.2])
 
# 列表转tensor 
list_1=[2,3.2]
d=torch.Tensor(list_1) #  torch.set_default_tensor_type(torch.FloatTensor) 这句话的作用 
# print(d.dtype) #torch.float32
 
# 一个小数直接转化成tensor 
t=torch.Tensor([3.01]) #torch.set_default_tensor_type(torch.FloatTensor) 这句话的作用 
print(t)
print(t.dtype)
# tensor([3.0100])
# torch.float32
 
# 一个整数直接转化成 tensor 
y=torch.Tensor([5]) #torch.set_default_tensor_type(torch.FloatTensor) 这句话的作用 
print(y)
print(y.dtype)
# tensor([5.])
# torch.float32
 
e=torch.Tensor(2) # 随机产生 数据tensor   #torch.set_default_tensor_type(torch.FloatTensor) 这句话的作用 
print(e)
print(e.dtype)
# tensor([0.0000, 2.3125])
# torch.float32

# np.array 矩阵填充到固定长度

In [ ]:
appended = np.zeros((20,5))
appended[10:, :] = np.ones((1,5))[0]
print(appended)

# 生成器：a=(x*2 for x in range(10))

1、什么是生成器？
生成器仅仅保存了一套生成数值的算法，并且没有让这个算法现在就开始执行，而是我什么时候调它，它什么时候开始计算一个新的值，并给你返回。

2、为什么要用生成器？
列表所有数据都在内存中，如果有海量数据的话将会非常耗内存。
如：仅仅需要访问前面几个元素，那后面绝大多数元素占用的空间都白白浪费了。
如果列表元素按照某种算法推算出来，那我们就可以在循环的过程中不断推算出后续的元素，这样就不必创建完整的list，从而节省大量的空间。
简单一句话：我又想要得到庞大的数据，又想让它占用空间少，那就用生成器

In [15]:
a=(x*2 for x in range(10))
print(list(a)) 

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [14]:
a=(x*2 for x in range(10))
print(a) 
for i in a:print(i)

<generator object <genexpr> at 0x000002500A3163C0>
0
2
4
6
8
10
12
14
16
18


方法二， 如果一个函数中包含yield关键字，那么这个函数就不再是一个普通函数，而是一个generator。调用函数就是创建了一个生成器（generator）对象。

In [17]:
# yield
# 就是在程序中返回某个值，返回之后程序就不再往下运行了。
# 下一次调用这个函数的时候会接着这个 yield 的下一句代码执行。
def foo():
    print("starting...")
    while True:
        res = yield 4
        print("res:",res)
g = foo()
print(next(g))
print("*"*20)
print(next(g))
print("*"*20)
print(g.send(7))

starting...
4
********************
res: None
4
********************
res: 7
4


1.程序开始执行以后，因为foo函数中有yield关键字，所以foo函数并不会真的执行，而是先得到一个生成器g(相当于一个对象)

2.直到调用next方法，foo函数正式开始执行，先执行foo函数中的print方法，然后进入while循环

3.程序遇到yield关键字，然后把yield想想成return,return了一个4之后，程序停止，并没有执行赋值给res操作，此时next(g)语句执行完成，所以输出的前两行（第一个是while上面的print的结果,第二个是return出的结果）是执行print(next(g))的结果，

4.程序执行print("*"*20)，输出20个*

5.又开始执行下面的print(next(g)),这个时候和上面那个差不多，不过不同的是，这个时候是从刚才那个next程序停止的地方开始执行的，也就是要执行res的赋值操作，这时候要注意，这个时候赋值操作的右边是没有值的（因为刚才那个是return出去了，并没有给赋值操作的左边传参数），所以这个时候res赋值是None,所以接着下面的输出就是res:None,

6.程序会继续在while里执行，又一次碰到yield,这个时候同样return 出4，然后程序停止，print函数输出的4就是这次return出的4.

7.程序执行g.send(7)，程序会从yield关键字那一行继续向下运行，send会把7这个值赋值给res变量

8.由于send方法中包含next()方法，所以程序会继续向下运行执行print方法，然后再次进入while循环

9.程序执行再次遇到yield关键字，yield会返回后面的值后，程序再次暂停，直到再次调用next方法或send方法。

# pandas datetime 模块的使用：

In [ ]:
# 先用这个函数来识别这一列 ：
train2018['Time_time'] = pd.to_datetime(train2018['Time'])
train2019['Time_time'] = pd.to_datetime(train2019['Time'])
train2020['Time_time'] = pd.to_datetime(train2020['Time'])
test['Time_time'] = pd.to_datetime(test['Time'])
 
 
# 就可以根据这个固定的格式来进行筛选了
 
train2019Mon2 = train2019[(train2019['Time_time'] >= '2019-2-1') & (train2019['Time_time'] <= '2019-2-28')]
train2019Mon1 = train2019[(train2019['Time_time'] >= '2019-1-1') & (train2019['Time_time'] <= '2019-1-28')]

# 匿名函数 ：a= lambda x,y: (x*y+1,y**2)

In [35]:
a= lambda x,y: (x*y+1,y**2)
# a= lambda x,y: [x*y+1,y**2]
#    输入变量：  输入的变量进行什么操作
print(a(3,2))
b=a(1,2)
print(type(b))
print(b)

(7, 4)
<class 'tuple'>
(3, 4)


# apply

In [12]:
#函数应用和映射
import numpy as np
import pandas as pd
df=pd.DataFrame(np.random.randn(4,3),columns=list('bde'),index=['utah','ohio','texas','oregon'])
print('df:\n',df)
"""
               b         d         e
utah   -0.667969  1.974801  0.738890
ohio   -0.896774 -0.790914  0.474183
texas   0.043476  0.890176 -0.662676
oregon  0.701109 -2.238288 -0.154442
"""
 
#将函数应用到由各列或行形成的一维数组上。DataFrame的apply方法可以实现此功能
f=lambda x:x.max()-x.min()
#默认情况下会以列为单位，分别对列应用函数
t1=df.apply(f)
print('t1:\n',t1)
t2=df.apply(f,axis=1)
print('t2:\n',t2)
 
"""
b    1.597883
d    4.213089
e    1.401566
dtype: float64
utah      2.642770
ohio      1.370957
texas     1.552852
oregon    2.939397
dtype: float64
"""
 
#除标量外，传递给apply的函数还可以返回由多个值组成的Series
def f(x):
    return pd.Series([x.min(),x.max()],index=['min','max'])
t3=df.apply(f)
#从运行的结果可以看出，按列调用的顺序，调用函数运行的结果在右边依次追加
print('t3:\n',t3)
 
"""
            b         d         e
min -0.896774 -2.238288 -0.662676
max  0.701109  1.974801  0.738890
"""
 
#元素级的python函数，将函数应用到每一个元素
#将DataFrame中的各个浮点值保留两位小数
f=lambda x: '%.2f'%x
t3=df.applymap(f)
print('t3:\n',t3)
"""
            b      d      e
utah    -0.67   1.97   0.74
ohio    -0.90  -0.79   0.47
texas    0.04   0.89  -0.66
oregon   0.70  -2.24  -0.15
"""
 
#注意，之所以这里用map,是因为Series有一个元素级函数的map方法。而dataframe只有applymap。
t4=df['e'].map(f)
print('t4:\n',t4)
 
"""
utah     0.74
ohio     0.47
texas   -0.66
oregon  -0.15
"""

df:
                b         d         e
utah   -0.037644  0.288407  0.952890
ohio   -1.601297  0.075755 -0.310165
texas  -1.070995 -0.251691  0.670183
oregon  1.706271  1.642536 -0.806289
t1:
 b    3.307568
d    1.894227
e    1.759178
dtype: float64
t2:
 utah      0.990534
ohio      1.677052
texas     1.741178
oregon    2.512560
dtype: float64
t3:
             b         d         e
min -1.601297 -0.251691 -0.806289
max  1.706271  1.642536  0.952890
t3:
             b      d      e
utah    -0.04   0.29   0.95
ohio    -1.60   0.08  -0.31
texas   -1.07  -0.25   0.67
oregon   1.71   1.64  -0.81
t4:
 utah       0.95
ohio      -0.31
texas      0.67
oregon    -0.81
Name: e, dtype: object


'\nutah     0.74\nohio     0.47\ntexas   -0.66\noregon  -0.15\n'

# 异常处理：

In [ ]:
try:
    data=pd.read_csv("www.csv")
except : # 跳过所有类型的异常  也可以写上异常的命名称
    print ("Error: 没有找到文件或读取文件失败")

# pandas  DataFrame表格 

In [ ]:
# 生成空dataframe
ip_id=pd.DataFrame(columns=["user_id","ip",'judgetime'])

# 两个dataframe相连接，append
df1 = df1.append(df2) # 一定要再赋值回去

In [ ]:
# 删除重复的行
df.drop_duplicates()             #保留第一个值，返回副本
df.drop_duplicates(keep='last')  #保留最后一个值，返回副本
df.drop_duplicates(keep=False)   #删除所有重复值，返回副本
df.drop_duplicates('k1')         #删除第一列重复值，返回副本
df.drop_duplicates(['k1','k2'])  #删除全部列重复值，返回副本

In [20]:
# 根据某一列数值进行排序
# 按照行生成 DataFrame
daliebiao=[]
daliebiao.append(["wang",5,])
daliebiao.append(["song",1,])
daliebiao.append(["chen",0])
columns=["名字","idx"]
 
df=pd.DataFrame(data=daliebiao,columns=columns)
print(df)
df=df.sort_values('idx').drop_duplicates() 
print(df)

     名字  idx
0  wang    5
1  song    1
2  chen    0
     名字  idx
2  chen    0
1  song    1
0  wang    5


In [25]:
# 集合嵌套for 循环生成 
jihe={"我是第"+str(i)+"个":i for i in range(5) }
jihe

{'我是第0个': 0, '我是第1个': 1, '我是第2个': 2, '我是第3个': 3, '我是第4个': 4}

In [27]:
s=[1,2,3]
# [-1]:最后一个元素
print(s[-1])
# [-2]:倒数第二个元素
print(s[-2])

3
2


# 列表循环生成字典

In [28]:
b=[1,2,3,4,]
a={word: idx for idx, word in enumerate(b)}
b={idx: word for idx, word in enumerate(b)}
print(a)
print(b)

{1: 0, 2: 1, 3: 2, 4: 3}
{0: 1, 1: 2, 2: 3, 3: 4}


# 字符串列表　逆置

In [29]:
a = 'Python is a powerful languange.'
re_a = a[::-1]
print(re_a)

.egnaugnal lufrewop a si nohtyP


# 得到列表元素的下标

In [30]:
a = ['a', 'b', 'c', 'd', 'e', 'f']
 
a_i = a.index("b")
print(a_i)

1


# 把列表的元素转化成一个字符串

In [31]:
string = ['a','b','c','d','e','f','g']
s=''.join(string)
print(s)

abcdefg


# if else 语句 简写

In [32]:
a=0
a=100 if a>-1 else 1
print(a)
a=0
a="你好" if a>-1 else 1
print(a)

100
你好


# python 定义单链表结构 

In [33]:
class Node():
    '''定义单链表节点类'''
    def __init__(self,data,next = None):
        '''data为数据项，next为下一节点的链接，初始化节点默认链接为None'''
        self.data = data
        self.next = next
# 定义3个节点对象分别为node1、node2和node3
 
node1 = Node(1,None)
node2 = Node(2,node1)
node3 = Node(3,node2)
print(node1.next,node2.next ,node3.next)
print(node1.data,node2.data ,node3.data)

None <__main__.Node object at 0x000002500A3120A0> <__main__.Node object at 0x000002500A3121F0>
1 2 3


# 列表元素逆置 

In [34]:
lists = [1,3,4,5,6,7,9,2]
# 切片
print(lists[::-1])

[2, 9, 7, 6, 5, 4, 3, 1]


# 获取目录文件下面的文件名称

In [35]:
query_namejpg= os.listdir("samples_test_support/query/0")
print(query_namejpg[0:10])

NameError: name 'os' is not defined

# for 循环的另一种写法 

In [37]:
num = [x for x in range(1,101,1)]
print(num)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]


# python 定义类 实例化类所需要的参数和外部传参数

In [39]:
class aceshi():
        def __init__(self,sum):
            self.sum=sum
            
        def call(self,d):
            return self.sum*d
aceshi=aceshi(4)  # 实例化对象  就相当于倪创建了一个对象 对象有sum 这个属性 然后你在实例化你这个对象的时候 要 把 sum这个属性赋值 
a=aceshi.call(4) # def call(self,d):对象中定义了一个函数 ，需要传入一个外部的参数 d 所以你先实例化 对象然后再从 外部传参数 ！ 
print(a)

class aceshi():
        def __init__(self,sum):
            self.sum=sum
            
        def call(self,d):
            return self.sum*d
a=aceshi(4).call(2)  # 实例化对象 
print(a)

16
8


# python 类传参数 def test_kwargs(first, *args, **kwargs):

In [40]:
# 正如前面所说的，args类型是一个tuple，而kwargs则是一个字典dict，并且args只能位于kwargs的前面。代码的运行结果如下
# **kwargs则是将一个可变的关键字参数的字典传给函数实参，同样参数列表长度可以为0或为其他值
# *args就是就是传递一个可变参数元组给函数实参 不是列表，这个参数列表的数目未知，甚至长度可以为0
def test_kwargs(first, *args, **kwargs):
        print('first: ', first)
        print(type(kwargs))
        for v in args:
          print ('v in  (args): ', v)
        for k, v in kwargs.items():
          print (k, v)
 
test_kwargs(1, 2, 3, 4, k1=5, k2=6,k3=0)

first:  1
<class 'dict'>
v in  (args):  2
v in  (args):  3
v in  (args):  4
k1 5
k2 6
k3 0


# python 类

In [41]:
class Dog():# 类的首字母要大写
    def __init__(self,name,age):
        # self会自动传递后边的参数 name,age 
        self.name=name
        self.age=age
        
    def sit(self):
        print(self.name.title())
        return self.name.title()+"—+sit()"
    
    def roll(self):
        print(self.age)
        
    def modify_age(self,name1):
        self.age=name1
        
class Dog_son(Dog):
        def __init__(self,name,age):#初始化父类的属性
            super().__init__(name,age) # super 超类 
            self.high="170" #子类新建的属性
            
        def high_1(self):
            print(self.name,self.age,self.high)
         
        def high_2(self):
            print(self.name,self.age,self.high)
            return self.name+"--"+self.age+"--"+self.high
        
        def roll(self):
            print("重写父类roll方法")
 
 
print("------类实例化+打印类属性值-------")      
my_dag=Dog("wang","19")
print(my_dag.name)
print(my_dag.age)
 
print("------类实例化+调用类函数-------")
sit=my_dag.sit()
roll=my_dag.roll()
print(sit)
print(roll)
 
print("------创建多个实例化类-------")
you_dog=Dog("周","26")
print(you_dog.name)
 
print("-----类：属性赋值-----")
Dog.name="王"
Dog.age="22"
print(Dog.name)
print(Dog.age)
 
print("-----类实例化：修改属性值-----")
you_dog.age="100"
print(you_dog.name)
print(you_dog.age)
 
print("-----类里定义函数：修改属性值-----")
her_dog=Dog("张","10")
her_dog.modify_age("30")
print(her_dog.age)
 
print("-----继承父类+子类新建赋值+函数操作-----")
a_dog=Dog_son("李","21")
 
print(a_dog.high_1())
print(a_dog.high_2())
 
print("-----继承父类+重写父类方法+子类调用父类方法+函数操作-----")
a_dog=Dog_son("李","21")
print(a_dog.sit())
print(a_dog.roll())

------类实例化+打印类属性值-------
wang
19
------类实例化+调用类函数-------
Wang
19
Wang—+sit()
None
------创建多个实例化类-------
周
-----类：属性赋值-----
王
22
-----类实例化：修改属性值-----
周
100
-----类里定义函数：修改属性值-----
30
-----继承父类+子类新建赋值+函数操作-----
李 21 170
None
李 21 170
李--21--170
-----继承父类+重写父类方法+子类调用父类方法+函数操作-----
李
李—+sit()
重写父类roll方法
None


# 类的注意事项和参数问题：

In [43]:
class Dog():# 类的首字母要大写
    def __init__(self,name,age):
        # self 这时候调用类或者实例化，必须传入参数！
        self.name="王"
        self.age="00"
    def prin(self):
        print(self.name,self.age)
a=Dog("张","10")# 传参也不管用 还是使用的：self.name="王" self.age="00"这两个参数 
print(a.prin())

王 00
None


In [44]:
class Dog_t():# 类的首字母要大写
    def __init__(self,name,age):
        # self 这时候调用类或者实例化，必须传入参数！
        self.name=name
        self.age=age
    def prin(self):
        print(self.name,self.age)
a=Dog_t("张","10")# 使用传入的参数,Dog_t("张","10")
print(a.prin())

张 10
None


In [45]:
class Dog_g():# 类的首字母要大写
    def __init__(self):
        # self后边没东西，这时候不需要串参数！
        self.name="wang"
        self.age="00"
    def prin(self):
        print(self.name,self.age)
a=Dog_g() # Dog("张","10") 传参会报错！
print(a.prin())

wang 00
None


# python计算阶乘

In [46]:
from functools import reduce
n = 3
print(reduce(lambda x,y:x*y,range(1,n+1)))

6


# 生成全0的tensor

In [48]:
a=torch.zeros(1,8,dtype=torch.float64)[0]
print(a)

tensor([0., 0., 0., 0., 0., 0., 0., 0.], dtype=torch.float64)


# python内置函数

In [49]:
# 1)对于一个列表排序
sorted([100, 98, 102, 1, 40])

[1, 40, 98, 100, 102]

In [50]:
# 2)通过key参数/函数
# 比如一个长列表里面嵌套了很多字典元素，我们要按照每个元素的长度大小排序
L = [{1:5,3:4},{1:3,6:3},{1:1,2:4,5:6},{1:9}]
new_line=sorted(L,key=lambda x:len(x))
print(new_line)

[{1: 9}, {1: 5, 3: 4}, {1: 3, 6: 3}, {1: 1, 2: 4, 5: 6}]


In [51]:
# 3)对由tuple组成的List排序
students = [('wang', 'A', 15), ('li', 'B', 12), ('zhang', 'B', 10)]   
print(sorted(students, key=lambda student : student[2]))

[('zhang', 'B', 10), ('li', 'B', 12), ('wang', 'A', 15)]


In [52]:
# 4）用cmp函数排序
students = [('wang', 'A', 15), ('li', 'B', 12), ('zhang', 'B', 10)]   
print(sorted(students, cmp=lambda x,y : cmp(x[0], y[0])) )

TypeError: 'cmp' is an invalid keyword argument for sort()

2.map()

map可以根据提供的函数对指定序列做映射，它接受一个函数f和一个list,并通过把函数f以此作用在list上的每个元素，然后返回一个新的list,map函数的入参也可以是多个.注意这个函数一定要有返回值(值值值重要的说三遍)。不然就会返回新的list 类似[None, None, None, None, None, None, None, None, None]

https://blog.csdn.net/weixin_44799217/article/details/119799110

In [57]:
def fun(x):
    return x*x
result=map(fun,[1,2,3,4,5])
print(type(result))
print(list(result))

<class 'map'>
[1, 4, 9, 16, 25]


In [59]:
lst = ['1', '2', '3', '4', '5', '6']
print(lst)
lst_int = map(lambda x: int(x), lst)
# print(list(lst_int))
for i in lst_int:
    print(i, end=' ')
print()
print(list(lst_int))
# 因为map()生成的是迭代器，所以for循环后再使用lst_list时迭代器中的数据已经为空了

['1', '2', '3', '4', '5', '6']
1 2 3 4 5 6 
[]


# np.random的各种生成随机数方法

https://blog.csdn.net/weixin_39374967/article/details/103655190

# enumerate()

Python中，迭代永远是取出元素本身，而非元素的索引,有的时候我们需要知道元素的索引比如在一个很长的列表里面是一些网站名，我们希望在打印的时候，也能列出索引。若没有这个函数，我们需要在加一个变量，在循环打印的时候让这个计数变量递增，现在有了enumerate，就不用这么麻烦了，直接搞定.

In [47]:
list1 = ["这", "是", "一个", "测试"]

for i in range(len(list1)):
    print(i,list1[i])

print()
for index, item in enumerate(list1):
    print(index, item)

print()
for index, item in enumerate(list1,2):
    print(index, item)

0 这
1 是
2 一个
3 测试

0 这
1 是
2 一个
3 测试

2 这
3 是
4 一个
5 测试


# zip()

zip函数接受任意多个（包括0个和1个）序列作为参数，返回一个tuple列表

In [44]:
x = [1, 2, 3]
y = [4, 5, 6]
z = [7, 8, 9]
xyz = zip(x, y, z)
print(type(xyz),xyz)
for i in xyz:
    print(i)

<class 'zip'> <zip object at 0x0000024F8776A800>
(1, 4, 7)
(2, 5, 8)
(3, 6, 9)


# filter()

filter函数接受一个函数f和一个list,这个函数f的作用是对每个元素进行判断,返回True或者False,这样可以过滤掉一些不符合条件的元素，然后返回符合条件的list.

In [50]:
def is_even(x):
    return x%2==0
fil=filter(is_even,[1,2,3,4,5])
print(type(fil),fil)
for i in fil:
    print(i)

<class 'filter'> <filter object at 0x0000024F876F06A0>
2
4


# reduce()

注意在python3里面reduce已经从全局函数里面移除了，需要用的话要from functools import reduce

reduce函数的用法和map很类似,也是一个函数f和一个list,但是函数的入口参数一定要是两个，reduce也是对每个元素进行反复调用，最后返回最终的值，而map是返回一个list

In [51]:
from functools import reduce

def add(x,y):
    return x+y
print(reduce(add,[1,2,3]))

6


# one_hot 编码转化

In [52]:
import tensorflow as tf
x=[1,2,3,2,1,3,4,5,4,3,2,1,1]
x_one_hot=tf.keras.utils.to_categorical(x)
print(x_one_hot)

[[0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]]


In [57]:
list1=[1,5,2,9,3]
sorted_id = sorted(range(len(list1)), key=lambda k: list1[k], reverse=False)# 对列表进行从小到大排序 返回 排序后原来元素的下标
print(sorted_id)

[0, 2, 4, 1, 3]


In [60]:
# me v 18340082396 py固定范围生成固定个数的随机数
import random
a= random.sample(range(0, 10), 5)
print(a)

[6, 7, 4, 2, 3]


In [61]:
# py固定范围产生一个随机小数
import random
t=random.uniform(0,1)
print(t)

0.9243585233880436


In [104]:
# if break 跳出for 循环 的先后问题
i = 0
while True:
    i = i + 1
    for j in range (1,10):
        if j >i:
            continue
        elif j == i :
            print('%i X %i = %i   '%(j,i,j*i))
        else:
            print('%i X %i = %i   ' % (j, i, j * i),end='')
    if i >= 9:
        break

for i in range (1,20):
    if i > 9 :
        break
    j = 0
    while j<20:
        j = j + 1
        if j>i:
            continue
        elif j == i :
            print('%i X %i = %i   '%(j,i,j*i))
        else:
            print('%i X %i = %i   ' % (j, i, j * i),end='')

1 X 1 = 1   
1 X 2 = 2   2 X 2 = 4   
1 X 3 = 3   2 X 3 = 6   3 X 3 = 9   
1 X 4 = 4   2 X 4 = 8   3 X 4 = 12   4 X 4 = 16   
1 X 5 = 5   2 X 5 = 10   3 X 5 = 15   4 X 5 = 20   5 X 5 = 25   
1 X 6 = 6   2 X 6 = 12   3 X 6 = 18   4 X 6 = 24   5 X 6 = 30   6 X 6 = 36   
1 X 7 = 7   2 X 7 = 14   3 X 7 = 21   4 X 7 = 28   5 X 7 = 35   6 X 7 = 42   7 X 7 = 49   
1 X 8 = 8   2 X 8 = 16   3 X 8 = 24   4 X 8 = 32   5 X 8 = 40   6 X 8 = 48   7 X 8 = 56   8 X 8 = 64   
1 X 9 = 9   2 X 9 = 18   3 X 9 = 27   4 X 9 = 36   5 X 9 = 45   6 X 9 = 54   7 X 9 = 63   8 X 9 = 72   9 X 9 = 81   
1 X 1 = 1   
1 X 2 = 2   2 X 2 = 4   
1 X 3 = 3   2 X 3 = 6   3 X 3 = 9   
1 X 4 = 4   2 X 4 = 8   3 X 4 = 12   4 X 4 = 16   
1 X 5 = 5   2 X 5 = 10   3 X 5 = 15   4 X 5 = 20   5 X 5 = 25   
1 X 6 = 6   2 X 6 = 12   3 X 6 = 18   4 X 6 = 24   5 X 6 = 30   6 X 6 = 36   
1 X 7 = 7   2 X 7 = 14   3 X 7 = 21   4 X 7 = 28   5 X 7 = 35   6 X 7 = 42   7 X 7 = 49   
1 X 8 = 8   2 X 8 = 16   3 X 8 = 24   4 X 8 = 32   5 X 8 = 

In [71]:
# 字典循环取值： 
dict = {"aa":11,"bb":22,"cc":33}
print(type(dict))
print(dict)

print()
for key in dict.keys():
    print(key)
    
print()
for value in dict.values():
    print(value)
    
print()
#取全部key值
key = dict.keys()
print(key)

print()
#输出value 值需要排序
for i  in sorted(dict.values()):
    print(i)

<class 'dict'>
{'aa': 11, 'bb': 22, 'cc': 33}

aa
bb
cc

11
22
33

dict_keys(['aa', 'bb', 'cc'])

11
22
33


In [99]:
# 列表值频率统计 Counter
from collections import Counter

list1=['aaa','bbb','aaa','bbb','ccc','aaa','ddd']
a=[]
b=[]
for key in Counter(list1).items():
    print(key)
    a.append(key[0])
    b.append(key[1])
print(a)
print(b)

print()
a=[]
b=[]
for key in Counter(list1):
    print(key)
    a.append(key[0])
    b.append(key[1])
print(a)
print(b)

print()
print(Counter(list1))
print(type(Counter(list1)))

print()
print (Counter(list1).most_common(2))



('aaa', 3)
('bbb', 2)
('ccc', 1)
('ddd', 1)
['aaa', 'bbb', 'ccc', 'ddd']
[3, 2, 1, 1]

aaa
bbb
ccc
ddd
['a', 'b', 'c', 'd']
['a', 'b', 'c', 'd']

Counter({'aaa': 3, 'bbb': 2, 'ccc': 1, 'ddd': 1})
<class 'collections.Counter'>

[('aaa', 3), ('bbb', 2)]


In [72]:
# 列表求均值 最大值 最小值 中位数
list1=[1,5,2,9,3]
print(np.mean(list1))# 均值
print(max(list1))# 最大值
print(min(list1))# 最小值
a=np.median(list1)# 中位数
print(a)

4.0
9
1
3.0


In [80]:
# tensor 取值
list1=[1,5,2,9,3]
a=torch.Tensor(list1)
print(a)
print(a[0])
print(a[0].item())

tensor([1., 5., 2., 9., 3.])
tensor(1.)
1.0


In [97]:
a=['1','2','3','4','5']
print('  '.join(a))
print('##'.join(a))

1  2  3  4  5
1##2##3##4##5


# for i in range ()

range()是一个函数， for i in range () 就是给i赋值：

比如 for i in range （1，3）：就是把1,2依次赋值给i

range () 函数的使用是这样的:

range(start, stop, step)，分别是起始、终止和步长

In [18]:
# range（3）即：从0到3，不包含3，即0,1,2
for i in range(3):
    print(i,' ',end='')
print()

# range(1,3) 即：从1到3，不包含3，即1,2
for i in range(1,3):
    print(i,' ',end='')
print()

# range（1,3,2）即：从1到3，每次增加2，因为1+2=3，所以输出只有1
# 第三个数字2是代表步长。如果不设置，就是默认步长为1
for i in range(1,9,2):
    print(i,' ',end='')
print()

0  1  2  
1  2  
1  3  5  7  


In [5]:
#读取 txt  读取 csv 打开任意格式的文件
import pandas as pd

data=pd.read_csv('./sucai/nextlinks.txt',encoding='utf-8',sep=' ',delimiter="\t")
print(data.values)

print()
model=[]
with open('./sucai/nextlinks.txt', 'r') as f:
    for line in f:
        model.append(line)
print(model)

print()
model1=model[-1].split(" ")[1:-1]
print(model1)

[['bb 1 2 3']
 ['ccc 1 2 4']
 ['dddd 1 2 3 1']
 ['eeeee 1 2 3 ']
 ['ffff 1 2 3 1 2']
 ['ggg 1 2 3 1 ']
 ['hh 1 2 ']
 ['i 1 2 3 1 2 ']]

['a 1 2 3\n', 'bb 1 2 3\n', 'ccc 1 2 4\n', 'dddd 1 2 3 1\n', 'eeeee 1 2 3 \n', 'ffff 1 2 3 1 2\n', 'ggg 1 2 3 1 \n', 'hh 1 2 \n', 'i 1 2 3 1 2 \n']

['1', '2', '3', '1', '2']


# 文件夹改名 + 文件先改名在移动
#题目要求：有这样的文件夹 然后要求合并到一个大的文件夹

为了避免重复应该先改名 然后再合并：

In [8]:
#文件改名代码：
import os
import shutil

Olddir=os.path.join("./sucai","a.jpg") #  原来的文件路径
Newdir=os.path.join("./",(str("new_")+"a.jpg")) #  新的文件路径
print(Olddir)
print(Newdir)
os.rename(Olddir,Newdir)

./sucai\a.jpg
./new_a.jpg


# 文件移动加改名：

In [10]:

import os
import shutil

for i in range(6,9,1): # 几个文件夹
    # 原文件夹
#     old_path = str(str("0")*(4-len(str(i)))+str(i))
    old_path="./sucai"
    # 查看原文件夹下所有的的文件
    filenames = os.listdir(old_path)
    target_path = "合并"     # 新文件夹
    if not os.path.exists(target_path):
        os.mkdir(target_path)
    print("filenames",filenames)
    for file in filenames:# 遍历每个图片文件
        #改名：
        Olddir=os.path.join( old_path+str("/"),file) #  原来的文件路径
        filename=os.path.splitext(file)[0]  #  文件名
        Newdir=os.path.join(str(old_path)+str("/"),str(str(i)+"_")+str(file)) #  新的文件路径
        os.rename(Olddir,Newdir)  # 改名
        # 将文件移动到新文件夹中
        shutil.move(Newdir, target_path)

filenames ['add.jpg', 'fix.jpg', 'hack.jpg', 'new_a.jpg', 'nextlinks.txt']
filenames []
filenames []


# 数据生成csv 

In [3]:
import torch
import pandas as pd

datas=[['a','1'],['b','2'],['c','3'],['d','4']]
print(type(datas))
columns=["zimu","num"]
df=pd.DataFrame(data=datas,columns=columns)
df.to_csv('./sucai/self_test.csv')
data=pd.read_csv('./sucai/self_test.csv',encoding='utf-8')# ,sep=' ',delimiter="\t"
print(data)

# 不要列头，不要索引，只要open,high两列。
# df.to_csv('9.csv',columns=['open','high'],index=False,header=False)

<class 'list'>
   Unnamed: 0 zimu  num
0           0    a    1
1           1    b    2
2           2    c    3
3           3    d    4


In [4]:
import csv
lst=['e','5']
out_f = open('./sucai/self_test.csv','a',newline='')
writer = csv.writer(out_f)
writer.writerow(lst)

out_f.close()

data=pd.read_csv('./sucai/self_test.csv',encoding='utf-8')# ,sep=' ',delimiter="\t"
print(data)

  Unnamed: 0 zimu  num
0          0    a  1.0
1          1    b  2.0
2          2    c  3.0
3          3    d  4.0
4          e    5  NaN


In [11]:
# list_to_csv
import csv
import pandas as pd 
name_list = [['zhangsan','12','男','汉'],
         ['lisi','34','男','回'],
         ['wangwu','58','女','汉']
        ]
for n in range(10):
    # newline是数据之间不加空行
    f = open('./list_to_csv.csv','a',newline = '')
    writer = csv.writer(f)
    writer.writerow(name_list)
    f.close()
    
header = ['姓名','年龄','性别','民族']
# encoding='utf_8_sig'防止中文乱码
test = pd.DataFrame(columns=header,data=name_list).to_csv('./list_to_csv.csv',encoding='utf_8_sig')

# dict_to_csv
import csv
import pandas as pd
header = ['姓名','年龄','性别','民族']
pd.DataFrame(datas).to_csv('./dict_to_csv.csv',encoding='utf_8_sig')

# array_to_csv
import numpy
a = numpy.array([ [1,2,3], [4,5,6], [7,8,9] ])
numpy.savetxt("./array_to_csv.csv", a, delimiter=",")

data=pd.read_csv('./list_to_csv.csv')# ,sep=' ',delimiter="\t"
print(data)

# 清空文件
f = open('./list_to_csv.csv','a',newline = '')
writer = csv.writer(f)
f.seek(0)
f.truncate()
f.close()

   Unnamed: 0        姓名  年龄 性别 民族
0           0  zhangsan  12  男  汉
1           1      lisi  34  男  回
2           2    wangwu  58  女  汉


In [100]:
#seg是一个引号逗号的列表 ，然后生成一个空格分割的文本
seg=["11","ss","334e"]
seg=" ".join(i for i in seg)
print(seg)

11 ss 334e


In [32]:
#把数据从gpu拿到cpu 
import torch
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
outputs = [1,5,3,2]
outputs=torch.Tensor(outputs)
outputs=outputs.to(device)
print(type(outputs),outputs)

outputs = outputs.cpu()
print(type(outputs),outputs)

outputs=outputs.to(device)
outputs = outputs.cpu().numpy()
print(type(outputs),outputs)

<class 'torch.Tensor'> tensor([1., 5., 3., 2.], device='cuda:0')
<class 'torch.Tensor'> tensor([1., 5., 3., 2.])
<class 'numpy.ndarray'> [1. 5. 3. 2.]


In [44]:
# nn.Embedding(20,3)
import torch
from torch import nn

embedding=nn.Embedding(20,3)
input=torch.LongTensor([[1,2,4,5],[4,3,2,9]])
embedding(input)

tensor([[[-0.8323,  0.1582, -0.3030],
         [-0.4111,  0.1960,  1.0642],
         [-0.4625,  0.5564, -1.8883],
         [-1.3906, -2.2485, -0.9212]],

        [[-0.4625,  0.5564, -1.8883],
         [-2.3982, -1.3637, -1.2059],
         [-0.4111,  0.1960,  1.0642],
         [-0.2687,  0.4600, -0.2904]]], grad_fn=<EmbeddingBackward>)

In [53]:
a=[[1,2,3] for i in range(5)]
print(a)

[[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]]


In [48]:
#torch.cat((A,B),1)#按维数0（行）拼接
import torch
A=torch.ones(4,3) #2x3的张量（矩阵）                                     
B=2*torch.ones(4,3)#4x3的张量（矩阵）                                    
print(A)
print(B)
C=torch.cat((A,B),1)#按维数0（行）拼接
print(C)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])
tensor([[1., 1., 1., 2., 2., 2.],
        [1., 1., 1., 2., 2., 2.],
        [1., 1., 1., 2., 2., 2.],
        [1., 1., 1., 2., 2., 2.]])


In [47]:
import torch
A=torch.ones(4,3) #2x3的张量（矩阵）                                     
B=2*torch.ones(4,3)#4x3的张量（矩阵）                                    
print(A)
print(B)
C=torch.cat((A,B),0)#按维数0（行）拼接
print(C)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


In [46]:
#torch.bmm(batch1, batch2)
# 并且相乘的两个矩阵，要满足一定的维度要求：input（p,m,n) * mat2(p,n,a) ->output(p,m,a)。

import torch
batch1 = torch.randn(8, 2, 6)
batch2 = torch.randn(8, 6, 10)
res = torch.bmm(batch1, batch2)
print(res.size())

torch.Size([8, 2, 10])


# torch.topk(）
torch.topk(input, k, dim=None, largest=True, sorted=True, out=None) -> (Tensor, LongTensor)
沿给定dim维度返回输入张量input中 k 个最大值。
如果不指定dim，则默认为input的最后一维。
如果为largest为 False ，则返回最小的 k 个值。
返回一个元组 (values,indices)，其中indices是原始输入张量input中测元素下标。
如果设定布尔值sorted 为_True_，将会确保返回的 k 个值被排序。

In [54]:
import torch
pred=torch.randn((4,5))
print(pred)
values,indices=pred.topk(1,dim=1,largest=True,sorted=True)
print(values)
print(indices)

tensor([[ 0.4765,  1.1024, -1.0080,  0.2376, -0.9892],
        [ 0.6440,  0.2181, -2.3090,  0.7996, -0.9095],
        [ 0.1241, -0.4557, -1.9573,  0.8361, -0.0923],
        [-0.4670,  0.7174, -1.9417, -0.4731,  0.6780]])
tensor([[1.1024],
        [0.7996],
        [0.8361],
        [0.7174]])
tensor([[1],
        [3],
        [3],
        [1]])


In [55]:
import torch
pred=torch.randn((4,5))
print(pred)
values,indices=pred.topk(1,dim=0,largest=True,sorted=True)
print(values)
print(indices)

tensor([[-1.2380,  0.0138,  0.1253,  1.9651,  0.5429],
        [-0.2685, -1.0218, -1.0218, -1.7494, -0.9224],
        [-1.6383,  0.7148, -0.9548,  0.0421, -0.8530],
        [-0.0253, -0.6840, -0.9118, -0.9748,  0.2978]])
tensor([[-0.0253,  0.7148,  0.1253,  1.9651,  0.5429]])
tensor([[3, 2, 0, 0, 0]])


# Numpy中对向量、矩阵的使用详解

In [1]:
# 加载numpy库
import numpy as np
from scipy import sparse

# 创建一个一维数组表示一个行向量
vector_row = np.array([1, 2, 3])

# 创建一个一维数组表示一个列向量
vector_column = np.array([[1], [2], [3]])

# 创建一个二维数组表示一个矩阵
matrix1 = np.array([[1, 2], [1, 2], [1, 2]])

# 利用Numpy内置矩阵数据结构
matrix1_object = np.mat([[1, 2], [1, 2], [1, 2]])

# 创建一个新的矩阵
matrix2 = np.array([[0, 0], [0, 1], [3, 0]])

# 创建一个压缩的稀疏行(CSR)矩阵
matrix2_sparse = sparse.csc_matrix(matrix2)

# 查看稀疏矩阵
print(matrix2_sparse)

# 创建一个更大的矩阵
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
             [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
             [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

# 创建一个CSR矩阵
matrix_large_sparse = sparse.csr_matrix(matrix_large)

# 查看更大的稀疏矩阵
print(matrix_large_sparse)

# 创建一个行向量
vector = np.array([1, 2, 3, 4, 5, 6])

# 创建矩阵
matrix_vector = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 选择向量的第三个元素
print(vector[2])

# 选择第二行第二列
print(matrix_vector[1, 1])

# 选取一个向量的所有元素
print(vector[:])

# 选取从0开始一直到第3个（包含第3个）元素
print(vector[:3])

# 选取第3个元素之后的全部元素
print(vector[3:])

# 选取最后一个元素
print(vector[-1])

# 选取矩阵的第1行和第2行以及所有列
print(matrix_vector[:2, :])

# 选取所有行以及第2列
print(matrix_vector[:, 1:2])

# 选取所有行以及第2列并转换成一个新的行向量
print(matrix_vector[:, 1])

# 创建新的矩阵
matrix3 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# 查看行数和列数
print(matrix3.shape)

# 查看元素数量
print(matrix3.size)

# 查看维数
print(matrix3.ndim)

# 下面使用的矩阵是matrix_vector
# 创建一个匿名函数，返回输入值加上100以后的值
add_100 = lambda i: i+100

# 创建向量转化函数
vectorized_add_100 = np.vectorize(add_100)

# 对矩阵的所有元素应用这个函数
print(vectorized_add_100(matrix_vector))

# 用后矩阵本身不变
print(matrix_vector)

# 连续使用
print(vectorized_add_100(vectorized_add_100(matrix_vector)))

# 返回最大的元素
print(np.max(matrix_vector))

# 返回最小元素
print(np.min(matrix_vector))

# 找到每一列的最大元素
print(np.max(matrix_vector, axis=0))

# 找到每一行最大的元素
print(np.max(matrix_vector, axis=1))

# 返回平均值
print(np.mean(matrix_vector))

# 返回方差
print(np.var(matrix_vector))

# 返回标准差
print(np.std(matrix_vector))

# 求每一列的平均值
print(np.mean(matrix_vector, axis=0))

# 求每一行的方差
print(np.var(matrix_vector, axis=1))

# 将matrix3矩阵变为2×6矩阵
matrix4 = matrix3.reshape(2, 6)
print(matrix4)

# 上面的变形要求前后元素个数相同，且不会改变元素个数
print(matrix4.size)

# reshape时传入参数-1意味着可以根据需要填充元素
print(matrix3.reshape(1, -1))

# reshape如果提供一个整数，那么reshape会返回一个长度为该整数值的一维数组
print(matrix3.reshape(12))

# 转置matrix_vector矩阵
print(matrix_vector.T)

# 严格地讲，向量是不能被转置的
print(vector.T)

# 转置向量通常指二维数组表示形式下将行向量转换为列向量或者反向转换
print(np.array([[1, 2, 3, 4, 5, 6]]).T)

# 将matrix_vector矩阵展开
print(matrix_vector.flatten())

# 将矩阵展开的另一种策略是利用reshape创建一个行向量
print(matrix_vector.reshape(1, -1))

# 创建用于求秩的新矩阵
matrix5 = np.array([[1, 1, 1], [1, 1, 10], [1, 1, 15]])

# 计算矩阵matrix5的秩
print(np.linalg.matrix_rank(matrix5))

# 创建用于行列式求解的新矩阵
matrix6 = np.array([[1, 2, 3], [2, 4, 6], [3, 8, 9]])

# 求解矩阵matrix6的行列式
print(np.linalg.det(matrix6))

# 返回矩阵的对角线元素
print(matrix6.diagonal())

# 返回主对角线向上偏移量为1的对角线元素
print(matrix6.diagonal(offset=1))

# 返回主对角线向下偏移量为1的对角线元素
print(matrix6.diagonal(offset=-1))

# 返回矩阵的迹
print(matrix6.trace())

# 求迹的另外的方法（返回对角线元素并求和）
print(sum(matrix6.diagonal()))

# 创建一个求解特征值、特征向量的矩阵
matrix7 = np.array([[1, -1, 3], [1, 1, 6], [3, 8, 9]])

# 计算特征值和特征向量
eigenvalues, eigenvectors = np.linalg.eig(matrix7)

# 查看特征值
print(eigenvalues)

# 查看特征向量
print(eigenvectors)

# 构造两个点积（数量积）所需向量
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

# 计算点积
print(np.dot(vector_a, vector_b))

# Python 3.5+ 版本可以这样求解点积
print(vector_a @ vector_b)

# 构造两个可用于加减的矩阵
matrix_a = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 2]])
matrix_b = np.array([[1, 3, 1], [1, 3, 1], [1, 3, 8]])

# 两矩阵相加
print(np.add(matrix_a, matrix_b))

# 两矩阵相减
print(np.subtract(matrix_a, matrix_b))

# 直接用+/-也可以做矩阵加减
print(matrix_a + matrix_b)
print(matrix_a - matrix_b)

# 构造两个可用于乘法的小矩阵
matrix_c = np.array([[1, 1], [1, 2]])
matrix_d = np.array([[1, 3], [1, 2]])

# 两矩阵相乘
print(np.dot(matrix_c, matrix_d))

# Python 3.5+ 版本可以这样求解矩阵乘法
print(matrix_c @ matrix_d)

# 我们也可以把两矩阵对应元素相乘，而非矩阵乘法
print(matrix_c * matrix_d)

# 创建一个用于求逆的矩阵
matrix8 = np.array([[1, 4], [2, 5]])

# 计算矩阵的逆
print(np.linalg.inv(matrix8))

# 验证一个矩阵和它的逆矩阵相乘等于I（单位矩阵）
print(matrix8 @ np.linalg.inv(matrix8))

  (2, 0)	3
  (1, 1)	1
  (1, 1)	1
  (2, 0)	3
3
5
[1 2 3 4 5 6]
[1 2 3]
[4 5 6]
6
[[1 2 3]
 [4 5 6]]
[[2]
 [5]
 [8]]
[2 5 8]
(3, 4)
12
2
[[101 102 103]
 [104 105 106]
 [107 108 109]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[201 202 203]
 [204 205 206]
 [207 208 209]]
9
1
[7 8 9]
[3 6 9]
5.0
6.666666666666667
2.581988897471611
[4. 5. 6.]
[0.66666667 0.66666667 0.66666667]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
12
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[1 2 3 4 5 6]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5 6 7 8 9]]
2
0.0
[1 4 9]
[2 6]
[2 8]
14
14
[13.55075847  0.74003145 -3.29078992]
[[-0.17622017 -0.96677403 -0.53373322]
 [-0.435951    0.2053623  -0.64324848]
 [-0.88254925  0.15223105  0.54896288]]
32
32
[[ 2  4  2]
 [ 2  4  2]
 [ 2  4 10]]
[[ 0 -2  0]
 [ 0 -2  0]
 [ 0 -2 -6]]
[[ 2  4  2]
 [ 2  4  2]
 [ 2  4 10]]
[[ 0 -2  0]
 [ 0 -2  0]
 [ 0 -2 -6]]
[[2 5]
 [3 7]]
[[2 5]
 [3 7]]
[[1 3]
 [1 4]]
[[-1.66666667

# 运行不了

## 文本分词处理

In [ ]:
# juzi=[]
# for i in train_data:
#     zifuchuan=""
#     for ii in re.findall('[\u4E00-\u9FA5\\s]',i):
#         zifuchuan=zifuchuan+str(ii)
#     zifuchuan=zifuchuan.replace(" ","")
#     seg = jieba.lcut(zifuchuan)
#     seg=" ".join(i for i in seg)
#     juzi.append(seg)

In [ ]:
# #李雪莉 数据处理 
# zonghe=[]
# a=["01", "02", "03", "04", "05","06", "07", "08", "09", "10","12"]
# for i in a:
#     data=pd.read_excel("2020年社保医疗明细/医疗明细2020"+str(i)+".xlsx")
#     a=data.sum() # 数据按列求和
#     zonghe.append(a)
    
# data1=pd.read_excel("2020年社保医疗明细/医疗明细2020"+str("01")+".xlsx")
# print(len(data1.columns))
# print(data1.columns)

# zong=pd.DataFrame(np.array(zonghe))
# # print(zong)
# print(len(list(zong.sum())))
# print(list(zong.sum()))

In [ ]:
# #统计列表中相同元素得个数  然后取相同次数最多得前多少名画图 from collections import Counter
# from collections import Counter

# forword_wors_count=Counter(forword_wors)

# word=[]
# summ=[]
# for key in Counter(forword_wors_count).items():
#         word.append(key[0])
#         summ.append(key[1])
# sorted_id = sorted(range(len(summ)), key=lambda k: summ[k], reverse=True)

# sorted_word=[]
# for i in sorted_id[0:20]:
#     sorted_word.append(word[i])
# sorted_sum=[]
# for i in sorted_id[0:20]:
#     sorted_sum.append(summ[i])
# plt.rcParams["font.sans-serif"] = ['Simhei']
# plt.rcParams["axes.unicode_minus"] = False
# import pandas as pd
# import matplotlib.pyplot as plt
# plt.figure(figsize=(10,50))#设置画布的尺寸
# plt.title('词频统计图',fontsize=20)#标题，并设定字号大小
# plt.xlabel(u'词',fontsize=14)#设置x轴，并设定字号大小
# plt.ylabel(u'数目',fontsize=14)#设置y轴，并设定字号大小
 
# #alpha：透明度；width：柱子的宽度；facecolor：柱子填充色；edgecolor：柱子轮廓色；lw：柱子轮廓的宽度；label：图例；
# plt.bar(sorted_word,sorted_sum, alpha=0.2,width = 0.8,  facecolor = 'deeppink', edgecolor = 'darkblue', lw=1,)
# plt.legend(loc=2)#图例展示位置，数字代表第几象限
# plt.show()#显示图像

In [ ]:
# # pandas 基础

# datxt=pd.read_csv("./测试.txt",sep='\t',header=None,names=["1","2"])

# # 列分隔符  sep  # \t 空格  \n 表示换行    names 表示自己设置列名

# data.columns

# data[['w','z']]  # 选择表格中的'w'、'z'列

# df=df.fillna(0)# 所有的空值都填0 。df中的内容没有变。na代表空值 print(data.fillna(0)) 

# data.shape

# data.index

# data.dtypes

# data.describe()

# data["AQI"].unique() # 有多少个不一样的取值 

# data.cov()# 协方差 

# data.corr()

# # 删除 date这一列
# data.drop("date",axis=1)

# # 删除某一行 # 删除的是第一行 
# data.drop(0,axis=0) 

# # 每行求一个均值
# data.mean(axis=1) 

# # 每列求一个均值 
# data.mean(axis=0) 

# data["PM10"].corr(data["PM2.5"]) # 查看两列的相关系数

# # 创建Series dataframe中的一行或者一列数据 
# sdata=pd.Series([11,23,33,42],index=[1,2,3,4])
# print(sdata)

# sdata=pd.Series({1:"王",2:"33",3:"ee"})
# print(sdata)

# # 查询Series =查询字典
# print(sdata[1]) # 就是查询 1 对应的 王 

# # 自己创建dataframe-1
# data={
#     "数字":[1,2,3,4],
#     "字母":["w","e","r","t"]
    
# }
# sdata=pd.DataFrame(data)

# # 自己创建dataframe-2
# datas=[['a','1'],['b','2'],['c','3'],['d','4']]
# columns=["zimu","num"]
# df=pd.DataFrame(data=datas,columns=columns)

# data[['date', 'hour', 'AQI']]# 查询多列

# data.loc[1] # 查询一行  

# data.loc[1:9]#查询多行 把把最后一个9也包含了

# # 设置某一列数据来代替index, 这一列数据不删除：drop=False，删除是用True
# data.set_index("date",inplace=True,drop=False)

# # 查找值
# data.loc["20131205",["AQI","PM10"]] # 查询索引是20131205 列是 "AQI","PM10" 两个值 

# # 查询好几个索引的值 
# data.loc[["20201231","20131205"],["AQI","PM10"]]

# # 查询 值
# data["AQI"]==47.0 # 返回的是一个 Series 布尔值 

# # 条件查询
# data.loc[data["AQI"]==47.0,:]# 先选取行，后选取列：是取全部的列

# # 多条件查询 
# data.loc[(data["AQI"]==47.0)&(data["PM10"]<=12.0),:]

# # 统计一列数据的 数据分布
# data["AQI"].value_counts() # 每个值出现了多少次 

# # 列的修改：
# # 对某一列进行修改
# data.loc[:,"hour"]=0.00 # 把这一列的数据都设置为0

# data.loc[:,"hour"].astype("int32") # 修改数据类型 

# data.loc[:,"hour"]=data["AQI"]-data["PM10"]

# # 用汉字的描述来代替列数据中的值
# def aqi_react(x):
#     if x["PM10"]>100:
#         return "严重"
#     else:
#         return "一般"

# data.loc[:,"AQI"]=data.apply(aqi_react,axis=1)

# # 新增一列 不是在原来的数据上进行修改的 是产生了一个新的对象 
# a=data.assign(
#       xinzeng=data["AQI"] #列名是 xinzeng 
# )

# # 新建一列但是这一列数据是根据前边的数据操作而创建的
# data["条件创建列"]="" # 创建空列 
# data.loc[(data["PM2.5"]>80)&(data["PM10"]>80),"条件创建列"]="天气污染严重" # 对新建的空列进行赋值 

# # pandas缺失值的处理
# data=pd.read_excel("./第一部分.xlsx")# 有一个参数是 skiprows 是掠过几个空行的意思 
# data.isnull() # False True 来表示数据 
# data["AQI"].isnull() 

# # 筛选没有空值得 AQI 得所有行 
# data.loc[data["AQI"].notnull(),:]

# # 删除掉全是空值得列 
# data.dropna(axis="columns",how="all",inplace=True)

# #删除掉全是空值得行
# data.dropna(axis="index",how="all",inplace=True)

# # 把某列  数值 为空得值  填充为 什么 
# data["PM10"]=data["PM10"].fillna(2) # fillna(method="ffill") # 空值处使用前边得值进行填充 bfill 是后边得值进行填充 

# # pandas对数据进行排序 
# data.sort_values(by=["PM10"],ascending=False) #行根据某个值进行排序  False是降序 

# data.sort_values(by=["PM10","PM2.5"],ascending=[False,True]) #行根据多个列值 进行排序 升序还是降序 

# # pandas 索引的index的用处 
# # 随机打乱数据
# # 魔法函数看函数的执行时间  %timeit
# from sklearn.utils import shuffle
# %timeit data_sh=shuffle(data)

# # 按照某一列数据进行分组    
# df=data.groupby("date")
# df.head()